apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-backend
  template:
    metadata:
      labels:
        app: ledger-backend
    spec:
      containers:
        - name: ledger-backend
          image: sm7rth/my-ledger-backend:22649aea4ca4249b63eb3002655eda93d21347fc
          ports:
            - containerPort: 2231
          envFrom:
            - secretRef:
                name: ledger-backend-secret # references decrypted secret

