apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-backend
  template:
    metadata:
      labels:
        app: ledger-backend
    spec:
      containers:
        - name: ledger-backend
          image: sm7rth/my-ledger-backend:6a4c88e167795c391c990170b2f1245375a8adb7
          ports:
            - containerPort: 2231
          envFrom:
            - secretRef:
                name: ledger-backend-secret # references decrypted secret
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_URL
              value: "redis://ledger-redis:6379" # Use the service name for Redis