apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-worker
  template:
    metadata:
      labels:
        app: ledger-worker
    spec:
      containers:
        - name: ledger-worker
          image: sm7rth/my-ledger-worker:b46642cabfa4b8bb72f81951b67072d60d9e9cfa
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: ledger-worker-secret # references decrypted secret
