apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-worker
  template:
    metadata:
      labels:
        app: ledger-worker
    spec:
      containers:
        - name: ledger-worker
          image: sm7rth/my-ledger-worker:latest
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: order-service-secret   # references decrypted secret