apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-worker
  template:
    metadata:
      labels:
        app: ledger-worker
    spec:
      containers:
        - name: ledger-worker
          image: sm7rth/my-ledger-worker:22649aea4ca4249b63eb3002655eda93d21347fc
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: ledger-worker-secret # references decrypted secret
