apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-worker
  template:
    metadata:
      labels:
        app: ledger-worker
    spec:
      containers:
        - name: ledger-worker
          image: sm7rth/my-ledger-worker:70bd48381e4c4b07fc09611088cb76283ecb2346
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: ledger-worker-secret # references decrypted secret
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_URL
              value: "redis://ledger-redis:6379" # Use the service name for
