apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-worker
  template:
    metadata:
      labels:
        app: ledger-worker
    spec:
      containers:
        - name: ledger-worker
          image: sm7rth/my-ledger-worker:58c20de7a6e8ba6987c5bae83fbcc54a7ead5bdd
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              value: "production"
            - name: REDIS_URL
              value: "redis://ledger-redis:6379" # Use the service name for
