apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ledger-worker
  template:
    metadata:
      labels:
        app: ledger-worker
    spec:
      containers:
        - name: ledger-worker
          image: sm7rth/my-ledger-worker:b02802e665333a506c6b6835a236ee1cba0f6349
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: ledger-worker-secret # references decrypted secret
