apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-backend
  template:
    metadata:
      labels:
        app: ledger-backend
    spec:
      containers:
        - name: ledger-backend
          image: sm7rth/my-ledger-backend:493c8ecad9552f766bb36f227a7e3bdffcf0ae27
          ports:
            - containerPort: 2231
          envFrom:
            - secretRef:
                name: ledger-backend-secret # references decrypted secret

