apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - myledger-app.ddnsfree.com
      secretName: myledger-app-tls
  rules:
    - host: myledger-app.ddnsfree.com
      http:
        paths:
          - path: /.well-known/acme-challenge/
            pathType: Prefix
            backend:
              service:
                name: cm-acme-http-solver
                port:
                  number: 8089
          - path: /api/v1/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ledger-backend-service
                port:
                  number: 80