---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ledger-worker-secret
  namespace: default
spec:
  encryptedData:
  template:
    metadata:
      creationTimestamp: null
      name: ledger-worker-secret
      namespace: default
