apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-ledger
spec:
  schedule: "0 0 * * *"   # Every day at 12 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-worker1
            image: curlimages/curl:latest
            command:
              - curl
              - -X
              - GET
              - "http://ledger-backend-service.default.svc.cluster.local/worker1"
          - name: curl-worker2
            image: curlimages/curl:latest
            command:
              - curl
              - -X
              - GET
              - "http://ledger-backend-service.default.svc.cluster.local/worker2"
          restartPolicy: Never

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-ledger-worker3
spec:
  schedule: "5 9 * * *"   # Every day at 4 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-worker3
            image: curlimages/curl:latest
            command:
              - curl
              - -X
              - GET
              - "http://ledger-backend-service.default.svc.cluster.local/worker3"
          restartPolicy: Never